snd-soc-samsung-slif-$(CONFIG_SND_SOC_SAMSUNG_SLIF) += slif_clk_table.o \
	slif_soc.o \
	slif.o \
	slif_util.o \
	slif_nm.o \
	slif_dump.o

# TODO: Build util, nm and dump only if target use older SLIF version

obj-$(CONFIG_SND_SOC_SAMSUNG_SLIF) += snd-soc-samsung-slif.o
